# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-javascript/ for more details
#
version: 2.1
executors:
  react-viewer-docker:
    docker:
      - image: cypress/base:8
commands:
  install-orient-express:
    description: 'Installs the orient express server either from cache or git clone'
    steps:
      - run:
          name: 'Fetch last commit hash from orient-express repo'
          command: curl --silent -u $GITHUB_USER:GITHUB_PASSWORD https://api.github.com/repos/lesfieres/orient-express/commits | head -3 | tail -1 | cut -c 13-52 > orient-express-last-commit-hash

      - restore_cache:
          keys:
            - v1-orient-express-{{ checksum "orient-express-last-commit-hash" }}

      - run:
          name: 'Checkout and npm install orient-express if not in cache'
          command: |
            ./.circleci/checkout-orient-express.sh
            ./.circleci/npm-install-orient-express.sh
      - run:
          name: 'Prepare .env'
          command: |
            cd orient-express
            echo -n 'GOODREADS_KEY=' >> .env
            echo $GOODREADS_KEY >> .env
            echo -n 'GOODREADS_SECRET=' >> .env
            echo $GOODREADS_SECRET >> .env
            echo -n 'OMBD_KEY=' >> .env
            echo $OMBD_KEY >> .env
      - save_cache:
          paths:
            - orient-express
          key: v1-orient-express-{{ checksum "orient-express-last-commit-hash" }}

  start-orient-express:
    description: 'Starts orient express server on background'
    steps:
      - run:
          name: 'Start orient-express server'
          background: true
          command: cd orient-express && npm run start
jobs:
  checkout_react-viewer:
    executor: react-viewer-docker
    working_directory: ~/repo
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  build_react-viewer:
    executor: react-viewer-docker
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v6-dependencies-{{ checksum "package.json" }}
      - run:
          name: 'Install dependencies if needed'
          command: ./.circleci/smart-npm-install.sh
      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache/Cypress
          key: v6-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
            - .npm
            - .cache/Cypress
  test_unit:
    executor: react-viewer-docker
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: 'Run unit tests'
          command: npm run test
  test_e2e:
    executor: react-viewer-docker
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - install-orient-express
      - start-orient-express
      - run:
          name: 'Run e2e tests'
          command: npm run test:e2e
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - checkout_react-viewer
      - build_react-viewer:
          requires:
            - checkout_react-viewer
      - test_unit:
          requires:
            - build_react-viewer
      - test_e2e:
          requires:
            - build_react-viewer
